### ISSUE TITLE
No token received

### ISSUE THREAD

**Issue by rockylca2014** [shirokumacode/overwatch-omnic-rewards#1] opened 2021-08-12 22:44 UTC
The program stats say i should get 150 token but when i launched the game i received none. I double check the account ID to make sure it match my account. not sure if it is related to 3 days getting error 404 during the program check time. Ill try it again tonight and see if i get any. I'm using eh current version exe file for window.
![Capture](https://user-images.githubusercontent.com/35970525/129279249-4c404629-59e9-4334-ac56-e74efa887e9a.PNG)

**Comment by shirokumacode** [comment] 2021-08-12 23:29
Have you compared the number of tokens before and after watching? Sometimes the yellow bar "Overwatch League tokens earned" in-game doesn't appear, especially if you get in a game right away, but the tokens are awarded.

Can you at least confirm you can get some tokens/skins with the app? If you are not getting any at all, I would suggest trying the website (should yield the same result, as this app mimics it) and then opening a ticket with Blizzard. I know some rare cases where accounts are bugged and don't seem to earn tokens at all.

Error 404 means the OWL page is probably down at that moment. If that happens you can restart the app or click "Check now" to see if it clears.

Note: The number of tokens displayed in the app might not be completely correct as Blizzard might cut the beginning/ending of stream and/or breaks from watch time. Take it as a estimation

**Comment by rockylca2014** [comment] 2021-08-13 01:01
Yes i have compare the token when i launch the game today and it doesnt increase by even one point. And though the website on the same machine using firefox i was able to get token. And for the error 404 i did refresh with the check now and it was watching the event like how it suppose to

**Comment by shirokumacode** [comment] 2021-08-13 01:23
So the problem is just today and you were able to earn tokens/skins through the app before, right?

The tokens can be delayed (normally it's instant). Even last weekend the people had problems with tokens and they had to be granted by Blizzard manually on monday and tuesday.

If you were able to earn tokens/skins before with the app, it's probably delayed tokens. This app behaves exactly like the website. 

Today I got 20tokens (3.58h watched + leftover time from last weekend) with the app, so it's working on my end.

**Comment by rockylca2014** [comment] 2021-08-13 01:30
ok so i think the token is delayed or my game is being corrupted since after i reinstall the game the token goes up lol. Man i love this game thanks again great program. I was thinking of doing something like that but way to complicate than your lol

**Comment by shirokumacode** [comment] 2021-08-13 01:53
Let me know if you have other problems. Also if you have a feature you would like, open a discussion and I'll implement it if it's feasible. Closing this issue for now

**Closed by shirokumacode** 2021-08-13 01:53 UTC
