### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by M0LLYxD** [shirokumacode/overwatch-omnic-rewards#31] opened 2022-08-19 15:43 UTC
Hello! Excuse me, does it work on Windows 7? No information about this.

**Comment by shirokumacode** [comment] 2022-08-19 23:05
Duplicate of #17 

> Python (latest versions) are currently unsupported in Windows 7 (as Microsoft no longer supports it). This project requires at least Python 3.9, which is not supported in Windows 7. Please update to a OS version that Microsoft is actively supporting (Python follows that).

**Closed by shirokumacode** 2022-08-19 23:05 UTC
